Repository sourceryinstitute/OpenCoarrays, pull requests merged in 2018-10, with the labels that each got.

#590 Bugfix remove aituning wrapper
  src/mpi/AITuning_OpenCoarrays.cpp
  src/mpi/Makefile
Labels: needs-review

#583 Use size_t for index argument
  src/mpi/mpi_caf.c
  src/openshmem/openshmem_caf.c
Labels: bug, confirmed, ready

#588 Issue #559 installer updates
  install.sh
  install.sh-usage
  prerequisites/build-functions/build_and_install.sh
  prerequisites/build.sh
  prerequisites/build.sh-usage
  prerequisites/install-functions/build_opencoarrays.sh
  prerequisites/install-functions/find_or_install.sh
  prerequisites/install-functions/print_header.sh
Labels: build-system, needs-review

#592 Fix #591 installer updates
  install.sh
  install.sh-usage
  prerequisites/acceptable_compiler.f90
  prerequisites/build-functions/set_or_print_default_version.sh
  prerequisites/build-functions/set_or_print_installation_path.sh
  prerequisites/build.sh-usage
  prerequisites/install-functions/build_opencoarrays.sh
  prerequisites/install-functions/find_or_install.sh
  prerequisites/install-functions/print_header.sh
Labels: needs-review

#593 Fix 2nd place where installer checks compiler ver.
  prerequisites/install-functions/find_or_install.sh
Labels: needs-review

#594 Switch insecure ftp URLs to secure https
  prerequisites/build-functions/set_or_print_url.sh
Labels: needs-review
